"""
Appointment Prep data models.

All models used by the appointment prep AI mode:
  - AI summary output schema (validated before patient review)
  - API request/response shapes
  - Session state TypedDict
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field, field_validator, model_validator
from typing_extensions import TypedDict

# ---------------------------------------------------------------------------
# Disclosure — backend-appended, never LLM-generated
# ---------------------------------------------------------------------------

_AI_DISCLOSURE = (
    "Generated by Sukshma-Jignaasa AI companion. "
    "This is not a medical diagnosis and cannot replace a clinical evaluation. "
    "Share with your healthcare provider as a starting point for discussion."
)

# ---------------------------------------------------------------------------
# Summary sub-types
# ---------------------------------------------------------------------------


class TopSymptom(BaseModel):
    """A symptom ranked by frequency and severity across the logging period."""

    name: str = Field(..., min_length=1, description="Human-readable symptom name")
    hpo_id: str | None = Field(None, description="HPO ID if available")
    body_system: str = Field(..., min_length=1)
    frequency: int = Field(..., ge=1, description="Number of times logged")
    avg_severity: float = Field(..., ge=1.0, le=10.0, description="Mean severity 1–10")
    last_observed: str = Field(..., description="ISO date of most recent log")

    @field_validator("avg_severity", mode="before")
    @classmethod
    def round_severity(cls, v: object) -> float:
        return round(float(v), 1)  # type: ignore[arg-type]


FrequencyLabel = Literal["frequently", "sometimes", "occasionally"]


class TriggerPattern(BaseModel):
    """A recurring trigger–symptom pattern detected in the logged history."""

    symptom: str = Field(..., min_length=1)
    trigger: str = Field(..., min_length=1)
    description: str = Field(
        ...,
        max_length=400,
        description="≤60 words, plain language, no clinical interpretation",
    )
    frequency_label: FrequencyLabel = "sometimes"


class SuggestedQuestion(BaseModel):
    """
    A question the patient could ask their specialist.
    Phrased as patient question, never as clinical conclusion.
    """

    question: str = Field(
        ...,
        max_length=300,
        description="Patient-facing question for their specialist",
    )
    context: str = Field(
        ...,
        max_length=300,
        description="Brief note on why this question is relevant to their logged symptoms",
    )

    @field_validator("question", mode="before")
    @classmethod
    def truncate_question(cls, v: object) -> str:
        s = str(v) if not isinstance(v, str) else v
        return s[:297] + "..." if len(s) > 300 else s

    @field_validator("context", mode="before")
    @classmethod
    def truncate_context(cls, v: object) -> str:
        s = str(v) if not isinstance(v, str) else v
        return s[:297] + "..." if len(s) > 300 else s


# ---------------------------------------------------------------------------
# Primary output schema
# ---------------------------------------------------------------------------


class AppointmentPrepSummary(BaseModel):
    """
    Full AI-generated appointment prep summary.
    ai_disclosure is always the canonical text — never LLM-generated.
    """

    patient_id: str
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    observation_count: int = Field(..., ge=0)
    date_range_start: str = Field(..., description="ISO date of earliest logged observation")
    date_range_end: str = Field(..., description="ISO date of most recent logged observation")

    top_symptoms: list[TopSymptom] = Field(
        default_factory=list,
        description="Up to 5 most significant symptoms by frequency × severity",
    )
    trigger_patterns: list[TriggerPattern] = Field(
        default_factory=list,
        description="Up to 4 notable trigger–symptom patterns",
    )
    suggested_questions: list[SuggestedQuestion] = Field(
        default_factory=list,
        description="Up to 5 questions the patient could bring to their specialist",
    )
    narrative: str = Field(
        ...,
        max_length=2000,
        description="≤250 words, plain-language overview of the symptom picture",
    )
    ai_disclosure: str = Field(
        default=_AI_DISCLOSURE,
        description="Always the canonical disclosure text — backend-appended",
    )
    human_approved: bool = False

    @field_validator("narrative", mode="before")
    @classmethod
    def truncate_narrative(cls, v: object) -> str:
        s = str(v) if not isinstance(v, str) else v
        return s[:1997] + "..." if len(s) > 2000 else s

    @model_validator(mode="after")
    def enforce_disclosure(self) -> "AppointmentPrepSummary":
        self.ai_disclosure = _AI_DISCLOSURE
        return self


# ---------------------------------------------------------------------------
# Session state TypedDict
# ---------------------------------------------------------------------------


class AppointmentPrepState(TypedDict):
    """State persisted in ai_sessions table between HTTP requests."""

    session_id: str
    patient_id: str
    observation_count: int

    # Serialised AppointmentPrepSummary; None until node completes
    prep_summary: dict | None

    # HITL
    human_approved: bool

    # Pipeline metadata
    status: str   # "running" | "awaiting_review" | "confirmed" | "failed"
    errors: list[str]


# ---------------------------------------------------------------------------
# API request / response models
# ---------------------------------------------------------------------------


class StartAppointmentPrepRequest(BaseModel):
    patient_id: str = Field(..., min_length=1)


class StartAppointmentPrepResponse(BaseModel):
    session_id: str
    patient_id: str
    status: str
    observations_available: int


class ConfirmAppointmentPrepRequest(BaseModel):
    decision: Literal["confirm", "regenerate"]
    feedback: str = Field(
        default="",
        description="Required when decision='regenerate' — patient's notes for improvement",
    )


class AppointmentPrepStatusResponse(BaseModel):
    session_id: str
    patient_id: str
    status: str
