"use client";

/**
 * ConfirmationCard — Step 3 of the check-in flow.
 * Shows the structured summary extracted by the AI.
 * Patient reviews, then taps Confirm & Save or Edit.
 * No FHIR write occurs until the patient confirms.
 */

import { useState } from "react";
import { useCheckInStore, type ConfirmationSummary } from "@/store/checkInStore";
import { checkInApi } from "@/lib/api";

interface Props {
  summary: ConfirmationSummary;
  onSaved: (observationIds: string[]) => void;
  onEdit: () => void;
}

export function ConfirmationCard({ summary, onSaved, onEdit }: Props) {
  const { sessionId, setSaved, setError, addMessage, setLoading, isLoading } =
    useCheckInStore();
  const [editMode, setEditMode] = useState(false);
  const [editNotes, setEditNotes] = useState("");

  const handleConfirm = async () => {
    if (!sessionId) return;
    setLoading(true);
    try {
      const res = await checkInApi.confirm(sessionId, "confirm");
      setSaved(res.fhir_observation_ids);
      onSaved(res.fhir_observation_ids);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Save failed.";
      setError(msg);
    } finally {
      setLoading(false);
    }
  };

  const handleEdit = async () => {
    if (!sessionId || !editNotes.trim()) return;
    setLoading(true);
    try {
      const res = await checkInApi.confirm(sessionId, "edit", editNotes.trim());
      addMessage({ role: "user", content: `Please update: ${editNotes.trim()}` });
      if (res.status === "in_progress" || res.status === "awaiting_confirmation") {
        onEdit();
      }
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Edit failed.";
      setError(msg);
    } finally {
      setLoading(false);
      setEditNotes("");
      setEditMode(false);
    }
  };

  return (
    <div className="space-y-5">
      <div>
        <h2 className="text-lg font-semibold text-slate-800 mb-1">Review your check-in</h2>
        <p className="text-sm text-slate-500">{summary.message}</p>
      </div>

      {/* No-symptom baseline */}
      {summary.is_no_symptom_day && (
        <div className="bg-brand-50 border border-brand-100 rounded-xl px-4 py-3 text-sm text-brand-700">
          ✓ Logging a no-symptom baseline for today.
        </div>
      )}

      {/* Symptom list */}
      {summary.symptoms.length > 0 && (
        <div className="space-y-2">
          <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wide">Symptoms captured</h3>
          {summary.symptoms.map((s, i) => (
            <div key={i} className="bg-white border border-slate-200 rounded-xl px-4 py-3 space-y-1">
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium text-slate-700">{s.text}</span>
                {s.severity !== null && (
                  <span className="text-xs font-bold text-brand-600 bg-brand-50 px-2 py-0.5 rounded-full">
                    {s.severity}/10
                  </span>
                )}
              </div>
              {s.hpo_labels.length > 0 && (
                <div className="flex flex-wrap gap-1">
                  {s.hpo_labels.map((label) => (
                    <span key={label} className="text-xs text-slate-500 bg-slate-100 px-2 py-0.5 rounded-full">
                      {label}
                    </span>
                  ))}
                </div>
              )}
              {s.trigger && (
                <p className="text-xs text-slate-500">Trigger: {s.trigger}</p>
              )}
            </div>
          ))}
        </div>
      )}

      {/* Context */}
      {Object.keys(summary.context).length > 0 && (
        <div className="bg-slate-50 rounded-xl px-4 py-3 text-sm text-slate-600">
          <h3 className="text-xs font-semibold uppercase tracking-wide mb-2 text-slate-500">Context</h3>
          <div className="flex flex-wrap gap-3">
            {summary.context.sleep_quality !== undefined && (
              <span>Sleep {String(summary.context.sleep_quality)}/10</span>
            )}
            {summary.context.stress_level !== undefined && (
              <span>Stress {String(summary.context.stress_level)}/10</span>
            )}
            {summary.context.activity_level !== undefined && (
              <span>Activity: {String(summary.context.activity_level)}</span>
            )}
          </div>
        </div>
      )}

      {/* Guardrail disclosure */}
      <p className="text-xs text-slate-400 italic">
        Generated by Sukshma-Jignaasa AI companion. Not a medical diagnosis.
        Discuss with your healthcare provider.
      </p>

      {/* Edit mode */}
      {editMode && (
        <div className="space-y-2">
          <textarea
            value={editNotes}
            onChange={(e) => setEditNotes(e.target.value)}
            placeholder="What would you like to correct? e.g. 'Change fatigue severity to 9'"
            rows={3}
            className="w-full resize-none rounded-xl border border-slate-200 px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"
          />
          <div className="flex gap-2">
            <button
              onClick={() => void handleEdit()}
              disabled={!editNotes.trim() || isLoading}
              className="flex-1 bg-brand-600 hover:bg-brand-700 disabled:opacity-50 text-white font-semibold py-3 rounded-xl transition-colors text-sm"
            >
              Submit edit
            </button>
            <button
              onClick={() => { setEditMode(false); setEditNotes(""); }}
              className="px-4 py-3 rounded-xl border border-slate-200 text-slate-600 text-sm hover:bg-slate-50"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* Actions */}
      {!editMode && (
        <div className="flex gap-3 pt-1">
          <button
            onClick={() => void handleConfirm()}
            disabled={isLoading}
            className="flex-1 bg-brand-600 hover:bg-brand-700 disabled:opacity-50 text-white font-semibold py-3 rounded-xl transition-colors"
          >
            {isLoading ? "Saving…" : "Confirm & Save"}
          </button>
          <button
            onClick={() => setEditMode(true)}
            disabled={isLoading}
            className="px-5 py-3 rounded-xl border border-slate-200 text-slate-600 text-sm font-medium hover:bg-slate-50 disabled:opacity-50"
          >
            Edit
          </button>
        </div>
      )}
    </div>
  );
}
