"""
PDF Service
-----------
Generates a formatted clinical report PDF from confirmed appointment-prep
and / or approved hypothesis data.

Returns raw bytes (PDF).  Caller is responsible for streaming the response.

Layout
------
  Page header: Sukshma-Jignaasa | Clinical Report | date
  Section 1 : Symptom Overview   (always present when prep included)
  Section 2 : Trigger Patterns   (always present when prep included)
  Section 3 : Suggested Questions(always present when prep included)
  Section 4 : Summary Narrative  (always present when prep included)
  Section 5 : Pattern Analysis   (only when hypothesis included)
  Page footer: AI disclosure on every page

All text is plain-language; no clinical interpretation added by this service.
"""
from __future__ import annotations

import io
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# ---------------------------------------------------------------------------
# Disclosure — identical to the one enforced in the model layer
# ---------------------------------------------------------------------------

_DISCLOSURE = (
    "Generated by Sukshma-Jignaasa AI companion. "
    "This is not a medical diagnosis and cannot replace a clinical evaluation. "
    "Share with your healthcare provider as a starting point for discussion."
)

_HYPOTHESIS_DISCLOSURE = (
    "The pattern profiles below highlight symptom similarities only. "
    "They are not a medical diagnosis and cannot replace a clinical evaluation. "
    "Please discuss any of these patterns with a specialist who can assess your full history."
)


# ---------------------------------------------------------------------------
# Style helpers
# ---------------------------------------------------------------------------

def _build_styles() -> dict:
    base = getSampleStyleSheet()
    s = {
        "title": ParagraphStyle(
            "title",
            parent=base["Title"],
            fontSize=20,
            leading=26,
            textColor=colors.HexColor("#1a1a2e"),
            alignment=TA_CENTER,
        ),
        "subtitle": ParagraphStyle(
            "subtitle",
            parent=base["Normal"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#555555"),
            alignment=TA_CENTER,
        ),
        "section_heading": ParagraphStyle(
            "section_heading",
            parent=base["Heading2"],
            fontSize=12,
            leading=16,
            textColor=colors.HexColor("#1a1a2e"),
            spaceBefore=10,
            spaceAfter=4,
        ),
        "body": ParagraphStyle(
            "body",
            parent=base["Normal"],
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#333333"),
        ),
        "bullet": ParagraphStyle(
            "bullet",
            parent=base["Normal"],
            fontSize=9,
            leading=13,
            leftIndent=12,
            bulletIndent=0,
            textColor=colors.HexColor("#333333"),
        ),
        "question_q": ParagraphStyle(
            "question_q",
            parent=base["Normal"],
            fontSize=9,
            leading=13,
            leftIndent=12,
            textColor=colors.HexColor("#1a1a2e"),
            fontName="Helvetica-Bold",
        ),
        "question_ctx": ParagraphStyle(
            "question_ctx",
            parent=base["Normal"],
            fontSize=8,
            leading=11,
            leftIndent=24,
            textColor=colors.HexColor("#666666"),
        ),
        "disclosure": ParagraphStyle(
            "disclosure",
            parent=base["Normal"],
            fontSize=7,
            leading=10,
            textColor=colors.HexColor("#888888"),
            alignment=TA_CENTER,
        ),
        "hypothesis_name": ParagraphStyle(
            "hypothesis_name",
            parent=base["Normal"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#1a1a2e"),
            fontName="Helvetica-Bold",
            spaceBefore=6,
        ),
        "hypothesis_body": ParagraphStyle(
            "hypothesis_body",
            parent=base["Normal"],
            fontSize=9,
            leading=13,
            leftIndent=10,
            textColor=colors.HexColor("#333333"),
        ),
    }
    return s


_BADGE_COLORS = {
    "high": colors.HexColor("#d32f2f"),
    "medium": colors.HexColor("#f57c00"),
    "low": colors.HexColor("#388e3c"),
}

_SEVERITY_BAR = "▓"  # filled block; we repeat it proportionally


def _severity_bar(avg: float) -> str:
    filled = round(avg)
    return _SEVERITY_BAR * filled + "░" * (10 - filled)


# ---------------------------------------------------------------------------
# Header / footer callback
# ---------------------------------------------------------------------------

def _make_header_footer(patient_id: str, generated_at: str):
    def _draw(canvas, doc):
        canvas.saveState()
        w, h = A4

        # Header line
        canvas.setStrokeColor(colors.HexColor("#1a1a2e"))
        canvas.setLineWidth(0.5)
        canvas.line(15 * mm, h - 18 * mm, w - 15 * mm, h - 18 * mm)

        canvas.setFont("Helvetica-Bold", 8)
        canvas.setFillColor(colors.HexColor("#1a1a2e"))
        canvas.drawString(15 * mm, h - 14 * mm, "Sukshma-Jignaasa  ·  Clinical Report")

        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(colors.HexColor("#888888"))
        canvas.drawRightString(w - 15 * mm, h - 14 * mm, f"Generated: {generated_at}")

        # Footer line
        canvas.line(15 * mm, 18 * mm, w - 15 * mm, 18 * mm)
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(colors.HexColor("#888888"))
        canvas.drawString(15 * mm, 12 * mm, _DISCLOSURE)
        canvas.drawRightString(w - 15 * mm, 12 * mm, f"Page {doc.page}")
        canvas.restoreState()

    return _draw


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

def _section_break(styles: dict) -> list:
    return [HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc")), Spacer(1, 4)]


def _build_prep_sections(prep: dict, styles: dict) -> list:
    """Build flowables for all appointment-prep sections."""
    story = []

    # ── Section 1: Symptom Overview ──────────────────────────────────────────
    story.append(Paragraph("1. Symptom Overview", styles["section_heading"]))
    story += _section_break(styles)

    date_start = prep.get("date_range_start", "")
    date_end = prep.get("date_range_end", "")
    obs_count = prep.get("observation_count", 0)
    story.append(Paragraph(
        f"Logging period: <b>{date_start}</b> to <b>{date_end}</b>  ·  "
        f"Total observations: <b>{obs_count}</b>",
        styles["body"],
    ))
    story.append(Spacer(1, 6))

    top_symptoms = prep.get("top_symptoms", [])
    if top_symptoms:
        table_data = [
            [
                Paragraph("<b>Symptom</b>", styles["body"]),
                Paragraph("<b>Body System</b>", styles["body"]),
                Paragraph("<b>Logged</b>", styles["body"]),
                Paragraph("<b>Avg Severity</b>", styles["body"]),
                Paragraph("<b>Last Logged</b>", styles["body"]),
            ]
        ]
        for s in top_symptoms[:5]:
            bar = _severity_bar(s.get("avg_severity", 5))
            table_data.append([
                Paragraph(s.get("name", ""), styles["body"]),
                Paragraph(s.get("body_system", "").replace("_", " ").title(), styles["body"]),
                Paragraph(str(s.get("frequency", "")), styles["body"]),
                Paragraph(f"{s.get('avg_severity', '')}/10  {bar}", styles["body"]),
                Paragraph(s.get("last_observed", ""), styles["body"]),
            ])
        col_widths = [55 * mm, 35 * mm, 20 * mm, 45 * mm, 25 * mm]
        t = Table(table_data, colWidths=col_widths, repeatRows=1)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#dddddd")),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(t)

    story.append(Spacer(1, 10))

    # ── Section 2: Trigger Patterns ───────────────────────────────────────────
    story.append(Paragraph("2. Trigger Patterns", styles["section_heading"]))
    story += _section_break(styles)

    patterns = prep.get("trigger_patterns", [])
    if patterns:
        for p in patterns:
            label = p.get("frequency_label", "sometimes").capitalize()
            story.append(Paragraph(
                f"• <b>{p.get('symptom', '')}</b> — {label} triggered by "
                f"<i>{p.get('trigger', '')}</i>",
                styles["bullet"],
            ))
            story.append(Paragraph(
                p.get("description", ""),
                styles["question_ctx"],
            ))
            story.append(Spacer(1, 4))
    else:
        story.append(Paragraph("No trigger patterns were logged during this period.", styles["body"]))

    story.append(Spacer(1, 6))

    # ── Section 3: Suggested Questions ───────────────────────────────────────
    story.append(Paragraph("3. Questions to Discuss with Your Specialist", styles["section_heading"]))
    story += _section_break(styles)

    questions = prep.get("suggested_questions", [])
    for i, q in enumerate(questions, 1):
        story.append(Paragraph(f"{i}. {q.get('question', '')}", styles["question_q"]))
        story.append(Paragraph(q.get("context", ""), styles["question_ctx"]))
        story.append(Spacer(1, 4))

    story.append(Spacer(1, 6))

    # ── Section 4: Summary Narrative ─────────────────────────────────────────
    story.append(Paragraph("4. Summary", styles["section_heading"]))
    story += _section_break(styles)
    story.append(Paragraph(prep.get("narrative", ""), styles["body"]))
    story.append(Spacer(1, 10))

    return story


def _build_hypothesis_section(hyp: dict, styles: dict) -> list:
    """Build flowables for the hypothesis / pattern analysis section."""
    story: list = []

    story.append(PageBreak())
    story.append(Paragraph("5. Pattern Analysis Profiles", styles["section_heading"]))
    story.append(Paragraph(
        "The following profiles describe symptom pattern similarities observed in your logged history. "
        "<b>These are not diagnoses.</b> They are presented to help you have an informed conversation "
        "with a specialist.",
        styles["body"],
    ))
    story += _section_break(styles)
    story.append(Spacer(1, 4))

    hypotheses = hyp.get("hypotheses", [])
    for i, h in enumerate(hypotheses, 1):
        strength = h.get("match_strength", "low")
        badge_color = _BADGE_COLORS.get(strength, colors.grey)
        name = h.get("condition_name", "")
        specialist = h.get("specialist_type", "")

        # Condition heading with match strength badge
        story.append(Paragraph(
            f"{i}. {name}  "
            f'<font color="{badge_color.hexval()}">[{strength.upper()} pattern similarity]</font>',
            styles["hypothesis_name"],
        ))
        story.append(Paragraph(
            h.get("plain_language_explanation", ""),
            styles["hypothesis_body"],
        ))
        story.append(Paragraph(
            f"<i>Confidence note:</i> {h.get('confidence_note', '')}",
            styles["question_ctx"],
        ))
        matching = h.get("matching_symptoms", [])
        if matching:
            story.append(Paragraph(
                "Matching symptoms logged: " + ", ".join(matching),
                styles["question_ctx"],
            ))
        story.append(Paragraph(
            f"<b>Recommended specialist type:</b> {specialist}",
            styles["hypothesis_body"],
        ))
        story.append(Spacer(1, 8))

    # Hypothesis disclosure
    story += _section_break(styles)
    story.append(Paragraph(_HYPOTHESIS_DISCLOSURE, styles["disclosure"]))
    story.append(Spacer(1, 6))

    return story


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def generate_clinical_report_pdf(
    patient_id: str,
    prep_summary: dict | None,
    hypothesis_report: dict | None,
) -> bytes:
    """
    Build the clinical report PDF and return the raw bytes.

    At least one of prep_summary or hypothesis_report must be provided.
    """
    buffer = io.BytesIO()
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    filename = f"sukshma-jignaasa-report-{patient_id[:8]}-{generated_at}.pdf"

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=15 * mm,
        leftMargin=15 * mm,
        topMargin=25 * mm,
        bottomMargin=25 * mm,
        title=filename,
        author="Sukshma-Jignaasa",
        subject="Clinical Report",
    )

    styles = _build_styles()
    on_page = _make_header_footer(patient_id, generated_at)

    story: list = []

    # ── Cover / title block ───────────────────────────────────────────────────
    story.append(Spacer(1, 10 * mm))
    story.append(Paragraph("Clinical Report", styles["title"]))
    story.append(Paragraph(
        f"Patient ID: {patient_id}  ·  Date: {generated_at}",
        styles["subtitle"],
    ))
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a1a2e")))
    story.append(Spacer(1, 10))

    # ── Appointment prep sections ─────────────────────────────────────────────
    if prep_summary:
        story += _build_prep_sections(prep_summary, styles)

    # ── Hypothesis section ────────────────────────────────────────────────────
    if hypothesis_report:
        story += _build_hypothesis_section(hypothesis_report, styles)

    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return buffer.getvalue()
